# Generated by Django 5.2.1 on 2025-05-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.company'),
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.company'),
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.category'),
        ),
        migrations.AddField(
            model_name='package',
            name='destination_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_packages', to='packages.branch'),
        ),
        migrations.AddField(
            model_name='package',
            name='origin_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_packages', to='packages.branch'),
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_packages', to='packages.agent'),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_packages', to='packages.agent'),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packagestatus'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.branch'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.company'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.driver'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='receiver_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tickets', to='packages.agent'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sender_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tickets', to='packages.agent'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.company'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.driver'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.vehicle'),
        ),
    ]
