# Generated by Django 5.2.1 on 2025-05-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender',
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(default='mugisha', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_phone',
            field=models.CharField(default=25078888888, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='sender_name',
            field=models.CharField(default='Gitera', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='sender_phone',
            field=models.CharField(default=250788410000, max_length=15),
            preserve_default=False,
        ),
    ]
