# Generated by Django 5.2.1 on 2025-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packagestatus_updated_at_packagestatus_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
