# Generated by Django 5.2.1 on 2025-05-15 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_package_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='plate_number',
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(default=1, limit_choices_to={'role__name': 'Agent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
