# Generated by Django 5.2.1 on 2025-05-16 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_fix_driver_user_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='receiver_phone',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sender_phone',
        ),
        migrations.RemoveField(
            model_name='packagestatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='receiver_agent',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sender_agent',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='value',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.AddField(
            model_name='ticket',
            name='package',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='packages.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_branch',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='destination_packages', to='packages.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin_branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='origin_packages', to='packages.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_packages', to='packages.agent'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender_agent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sent_packages', to='packages.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packagestatus',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='packagestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.branch'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='packages.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.driver'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=50),
        ),
    ]
