# Generated by Django 5.2.1 on 2025-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_add_fields_to_company_driver_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='nsengiyumva', max_length=255),
            preserve_default=False,
        ),
    ]
