# Generated by Django 5.2.1 on 2025-05-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_remove_driver_branch_remove_driver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='receiver_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_packages', to='packages.agent'),
        ),
    ]
