# Generated by Django 5.2.1 on 2025-05-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_package_sender_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(default='muhire', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_phone',
            field=models.CharField(default=7888777, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='sender_name',
            field=models.CharField(default='Kazungu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='sender_phone',
            field=models.CharField(default=78888990, max_length=20),
            preserve_default=False,
        ),
    ]
